version: '3.8'
services:
  # === Serwis dla aplikacji REACT ===
  react-app:
    build:
      context: react-testing-demo/ 
    ports:
      - "3000:3000" # Mapuj port 3000 na swoim komputerze do portu 3000 w kontenerze
    volumes:
      # Synchronizuj kod z folderu react-testing-demo z folderem /app w kontenerze
      - ./react-testing-demo:/app
      # Zapobiegaj nadpisywaniu node_modules w kontenerze przez lokalny folder
      - /app/node_modules
# === Serwis dla aplikacji ANGULAR ===
  angular-app:
    build:
      context: angular-testing-demo/
    ports:
      - "3001:4200" # Mapuj port 3001 na port 4200 (domyślny dla Angulara)
    volumes:
      - ./angular-testing-demo:/app
      - /app/node_modules

  # === Serwis dla aplikacji VUE ===
  vue-app:
    build:
      context: vue-testing-demo/
    ports:
      - "3002:5173" # Mapuj port 3002 na port 5173 (domyślny dla Vite/Vue)
    volumes:
      - ./vue-testing-demo:/app
      - /app/node_modules